
export const spriteSheet = {
    number1: {
        x: 0,
        y: 0,
        width: 13,
        height: 23,
    },
    number2: {
        x: 14,
        y: 0,
        width: 13,
        height: 23,
    },
    number3: {
        x: 28,
        y: 0,
        width: 13,
        height: 23,
    },
    number4: {
        x: 42,
        y: 0,
        width: 13,
        height: 23,
    },
    number5: {
        x: 56,
        y: 0,
        width: 13,
        height: 23,
    },
    number6: {
        x: 70,
        y: 0,
        width: 13,
        height: 23,
    },
    number7: {
        x: 84,
        y: 0,
        width: 13,
        height: 23,
    },
    number8: {
        x: 98,
        y: 0,
        width: 13,
        height: 23,
    },
    number9: {
        x: 112,
        y: 0,
        width: 13,
        height: 23,
    },
    number0: {
        x: 126,
        y: 0,
        width: 13,
        height: 23,
    },
    emoji1: {
        x: 0,
        y: 24,
        width: 27,
        height: 27,
    },
    emoji2: {
        x: 27,
        y: 24,
        width: 27,
        height: 27,
    },
    emoji3: {
        x: 54,
        y: 24,
        width: 27,
        height: 27,
    },
    emoji4: {
        x: 81,
        y: 24,
        width: 27,
        height: 27,
    },
    emoji5: {
        x: 108,
        y: 24,
        width: 27,
        height: 27,
    },
    gameItem1: {
        x: 0,
        y: 51,
        width: 16,
        height: 16,
    },
    gameItem2: {
        x: 17,
        y: 51,
        width: 16,
        height: 16,
    },
    gameItem3: {
        x: 34,
        y: 51,
        width: 16,
        height: 16,
    },
    gameItem4: {
        x: 51,
        y: 51,
        width: 16,
        height: 16,
    },
    gameItem5: {
        x: 68,
        y: 51,
        width: 16,
        height: 16,
    },
    gameItem6: {
        x: 85,
        y: 51,
        width: 16,
        height: 16,
    },
    gameItem7: {
        x: 102,
        y: 51,
        width: 16,
        height: 16,
    },
    gameItem8: {
        x: 119,
        y: 51,
        width: 16,
        height: 16,
    },
    gameItem9: {
        x: 0,
        y: 68,
        width: 16,
        height: 16,
    },
    gameItem10: {
        x: 17,
        y: 68,
        width: 16,
        height: 16,
    },
    gameItem11: {
        x: 34,
        y: 68,
        width: 16,
        height: 16,
    },
    gameItem12: {
        x: 51,
        y: 68,
        width: 16,
        height: 16,
    },
    gameItem13: {
        x: 68,
        y: 68,
        width: 16,
        height: 16,
    },
    gameItem14: {
        x: 85,
        y: 68,
        width: 16,
        height: 16,
    },
    gameItem15: {
        x: 102,
        y: 68,
        width: 16,
        height: 16,
    },
    gameItem16: {
        x: 119,
        y: 68,
        width: 16,
        height: 16,
    },
};
